import { createHash } from 'node:crypto';
import { lstat, realpath } from 'node:fs/promises';
import { relative, isAbsolute, join } from 'node:path';

export const CATALOG_LIMIT = 2000;
export interface CatalogArticle { path:string; frontmatter?:Record<string,unknown>; }
export interface CatalogEntry { path:string; title:string; category:string; }
export interface CatalogPlan { base:string; navigation:string; count:number; missing:Record<string,number>; entries:CatalogEntry[]; }

/** Refuse normalization surprises, hidden components, Windows aliases and streams. */
export function catalogPath(input:string, allowRoot=false):string {
  const path=input.trim();
  if(path!==input)throw Error('路径首尾不能包含空格');
  if (!path && allowRoot) return '';
  if (!path || path.length>240 || /[\\:*?"<>|\x00-\x1f]/.test(path) || path.startsWith('/') || path.endsWith('/')) throw Error('请输入库内相对路径，使用 / 分隔文件夹');
  for (const part of path.split('/')) {
    if (!part || part.startsWith('.') || /[. ]$/.test(part) || /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(part)) throw Error('路径不能包含隐藏目录、上级目录或系统保留名称');
  }
  return path;
}

/** Desktop only: reject every symlink/junction component, including internal links. */
export async function assertCatalogPath(root:string,path:string,allowMissing=false):Promise<void> {
  catalogPath(path,true);
  const base=await realpath(root);
  let current=base;
  for (const part of path.split('/').filter(Boolean)) {
    current=join(current,part);
    try {
      const stat=await lstat(current);
      if(stat.isSymbolicLink()) throw Error('目录整理不允许符号链接或 junction');
      const actual=await realpath(current), rel=relative(base,actual);
      if(rel==='..'||rel.startsWith(`..\\`)||rel.startsWith('../')||isAbsolute(rel)) throw Error('路径超出知识库');
    } catch(error:any) { if(error.code==='ENOENT'&&allowMissing) continue; throw error; }
  }
}
const text=(value:unknown):string=>typeof value==='string'?value.trim():typeof value==='number'?String(value):'';
const category=(fm:Record<string,unknown>):string=>text(Array.isArray(fm.category)?fm.category[0]:fm.category)||text(Array.isArray(fm.categories)?fm.categories[0]:fm.categories)||'未分类';
const present=(v:unknown):boolean=>Array.isArray(v)?v.length>0:typeof v==='boolean'||typeof v==='number'||(typeof v==='string'&&!!v.trim())||v instanceof Date;
const escapeLabel=(s:string)=>s.replace(/[\r\n]/g,' ').replace(/[\\\[\]`*_<>]/g,'\\$&');
const yaml=(s:string)=>JSON.stringify(s);

export function buildCatalog(articles:CatalogArticle[],source:string,output:string):CatalogPlan {
  source=catalogPath(source,true);output=catalogPath(output);
  if(articles.length>CATALOG_LIMIT) throw Error(`单次最多整理 ${CATALOG_LIMIT} 篇文章，请缩小目录范围`);
  const rows=articles.filter(a=>{
    catalogPath(a.path);
    return a.path.toLowerCase().endsWith('.md')&&(!source||a.path.startsWith(source+'/'))&&!a.path.startsWith(output+'/');
  }).sort((a,b)=>a.path.localeCompare(b.path));
  const filters=['file.ext == "md"',...(source?[`file.inFolder(${JSON.stringify(source)})`]:[]),`!file.inFolder(${JSON.stringify(output)})`];
  // Formulas keep the original frontmatter schema intact; dates are never inferred from mtime.
  const formulas:Record<string,string>={article:'file.asLink(if(title, title, file.name))',category:'if(category, category, if(categories, categories, "未分类"))',published:'if(date, date, pubDate)'};
  const columns=['formula.article','formula.category','note.tags','formula.published','note.draft'];
  const views=[{name:'全部文章'},{name:'按分类',group:true},{name:'草稿',draft:true}];
  const base=['# Generated by Deepsidian. Original articles are not modified.','filters:','  and:',...filters.map(f=>'    - '+yaml(f)),'formulas:',...Object.entries(formulas).map(([k,v])=>`  ${k}: ${yaml(v)}`),'properties:',...Object.entries({'formula.article':'文章','formula.category':'分类','note.tags':'标签','formula.published':'发布日期','note.draft':'草稿'}).flatMap(([k,v])=>[`  ${k}:`,`    displayName: ${yaml(v)}`]),'views:',...views.flatMap(v=>['  - type: table',`    name: ${yaml(v.name)}`,...(v.group?['    groupBy:','      property: formula.category','      direction: ASC']:[]),...(v.draft?['    filters:',`      and: [${yaml('draft == true')}]`]:[]),'    order:',...columns.map(c=>'      - '+c)]),''].join('\n');
  const missing={title:0,category:0,tags:0,published:0,draft:0};
  const groups=new Map<string,CatalogArticle[]>();
  for(const row of rows){
    const fm=row.frontmatter??{};
    if(!present(fm.title))missing.title++;
    if(!present(fm.category)&&!present(fm.categories))missing.category++;
    if(!present(fm.tags))missing.tags++;
    if(!present(fm.date)&&!present(fm.pubDate))missing.published++;
    if(typeof fm.draft!=='boolean')missing.draft++;
    const key=category(fm);groups.set(key,[...(groups.get(key)??[]),row]);
  }
  const navigation=['# 文章导航','',`扫描范围：${source?escapeLabel(source):'知识库根目录'}（排除 ${escapeLabel(output)}）。共 ${rows.length} 篇。`,'','这是生成时的静态导航；文章管理.base 会随文章属性变化更新。多分类文章在此按第一个分类归组。','',...Array.from(groups.entries()).sort(([a],[b])=>a.localeCompare(b)).flatMap(([name,items])=>[`## ${escapeLabel(name)}`,'',...items.map(a=>{
    const label=text(a.frontmatter?.title)||a.path.split('/').pop()!.replace(/\.md$/i,'');
    // Standard Markdown destinations encode #, brackets and whitespace without ambiguous wikilinks.
    const destination=a.path.split('/').map(s=>encodeURIComponent(s).replace(/[()']/g,c=>`%${c.charCodeAt(0).toString(16)}`)).join('/');
    const ups=output.split('/').map(()=> '..').join('/');
    return `- [${escapeLabel(label)}](${ups}/${destination})`;
  }), '']),'## 属性检查','',...Object.entries(missing).map(([key,n])=>`- ${key}：${n} 篇缺失${key==='draft'?'或不是布尔值':''}`),'','未推断分类、发布日期或学习掌握程度；未修改原文章。',''].join('\n');
  const entries=rows.map(a=>({path:a.path,title:text(a.frontmatter?.title)||a.path.split('/').pop()!.replace(/\.md$/i,''),category:category(a.frontmatter??{})}));
  return {base,navigation:managedNavigation(navigation,source,entries),count:rows.length,missing,entries};
}

const START='<!-- deepsidian-catalog:v1:';
const END='<!-- /deepsidian-catalog -->';
const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
function managedNavigation(body:string,source:string,entries:CatalogEntry[]):string {
  const state={source,entries,hash:digest({source,entries,body})};
  return `${START}${Buffer.from(JSON.stringify(state)).toString('base64')} -->\n${body}${END}\n`;
}
export function readNavigation(text:string) {
  const start=text.indexOf(START),end=text.indexOf(END);
  if(start<0||end<start||text.indexOf(START,start+1)>=0||text.indexOf(END,end+1)>=0)throw Error('导航缺少唯一的生成记录（旧版或手写文件），请保留原文件并选择新输出目录');
  const headerEnd=text.indexOf(' -->\n',start);
  if(headerEnd<0||headerEnd>end)throw Error('导航生成记录损坏，请保留原文件');
  let state:{source:string;entries:CatalogEntry[];hash:string};
  try {state=JSON.parse(Buffer.from(text.slice(start+START.length,headerEnd),'base64').toString('utf8'));}catch{throw Error('导航生成记录损坏，请保留原文件');}
  const body=text.slice(headerEnd+5,end);
  if(typeof state.source!=='string'||!Array.isArray(state.entries)||state.entries.length>CATALOG_LIMIT||state.hash!==digest({source:state.source,entries:state.entries,body}))throw Error('生成区域已被编辑或记录损坏；不会覆盖，请保留修改并使用新输出目录');
  return {source:state.source,entries:state.entries,start,end:end+END.length,body};
}
export function navigationUpdate(previous:string,plan:CatalogPlan,source:string) {
  const old=readNavigation(previous),next=readNavigation(plan.navigation);
  if(old.source!==source)throw Error('扫描范围与已有导航不同，请使用新的输出目录');
  const before=new Map(old.entries.map(e=>[e.path,e]));
  const after=new Map(plan.entries.map(e=>[e.path,e]));
  const added=plan.entries.filter(e=>!before.has(e.path));
  const removed=old.entries.filter(e=>!after.has(e.path));
  const changed=plan.entries.flatMap(e=>{const prev=before.get(e.path);return prev&&(prev.title!==e.title||prev.category!==e.category)?[{before:prev,after:e}]:[];});
  const replacement=plan.navigation.slice(next.start,next.end);
  return {text:previous.slice(0,old.start)+replacement+previous.slice(old.end),added,removed,changed};
}
