import { lstat, realpath } from 'node:fs/promises';
import { relative, isAbsolute, join } from 'node:path';

export const CATALOG_LIMIT = 2000;
export interface CatalogArticle { path:string; frontmatter?:Record<string,unknown>; }
export interface CatalogPlan { base:string; navigation:string; count:number; missing:Record<string,number>; }

/** Refuse normalization surprises, hidden components, Windows aliases and streams. */
export function catalogPath(input:string, allowRoot=false):string {
  const path=input.trim();
  if(path!==input)throw Error('路径首尾不能包含空格');
  if (!path && allowRoot) return '';
  if (!path || path.length>240 || /[\\:*?"<>|\x00-\x1f]/.test(path) || path.startsWith('/') || path.endsWith('/')) throw Error('请输入库内相对路径，使用 / 分隔文件夹');
  for (const part of path.split('/')) {
    if (!part || part.startsWith('.') || /[. ]$/.test(part) || /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(part)) throw Error('路径不能包含隐藏目录、上级目录或系统保留名称');
  }
  return path;
}

/** Desktop only: reject every symlink/junction component, including internal links. */
export async function assertCatalogPath(root:string,path:string,allowMissing=false):Promise<void> {
  catalogPath(path,true);
  const base=await realpath(root);
  let current=base;
  for (const part of path.split('/').filter(Boolean)) {
    current=join(current,part);
    try {
      const stat=await lstat(current);
      if(stat.isSymbolicLink()) throw Error('目录整理不允许符号链接或 junction');
      const actual=await realpath(current), rel=relative(base,actual);
      if(rel==='..'||rel.startsWith(`..\\`)||rel.startsWith('../')||isAbsolute(rel)) throw Error('路径超出知识库');
    } catch(error:any) { if(error.code==='ENOENT'&&allowMissing) continue; throw error; }
  }
}
const text=(value:unknown):string=>typeof value==='string'?value.trim():typeof value==='number'?String(value):'';
const category=(fm:Record<string,unknown>):string=>text(fm.category)||text(Array.isArray(fm.categories)?fm.categories[0]:fm.categories)||'未分类';
const present=(v:unknown):boolean=>Array.isArray(v)?v.length>0:typeof v==='boolean'||typeof v==='number'||(typeof v==='string'&&!!v.trim())||v instanceof Date;
const escapeLabel=(s:string)=>s.replace(/[\r\n]/g,' ').replace(/[\\\[\]`*_<>]/g,'\\$&');
const yaml=(s:string)=>JSON.stringify(s);

export function buildCatalog(articles:CatalogArticle[],source:string,output:string):CatalogPlan {
  source=catalogPath(source,true);output=catalogPath(output);
  if(articles.length>CATALOG_LIMIT) throw Error(`单次最多整理 ${CATALOG_LIMIT} 篇文章，请缩小目录范围`);
  const rows=articles.filter(a=>{
    catalogPath(a.path);
    return a.path.toLowerCase().endsWith('.md')&&(!source||a.path.startsWith(source+'/'))&&!a.path.startsWith(output+'/');
  }).sort((a,b)=>a.path.localeCompare(b.path));
  const filters=['file.ext == "md"',...(source?[`file.inFolder(${JSON.stringify(source)})`]:[]),`!file.inFolder(${JSON.stringify(output)})`];
  // Formulas keep the original frontmatter schema intact; dates are never inferred from mtime.
  const formulas:Record<string,string>={article:'file.asLink(if(title, title, file.name))',category:'if(category, category, if(categories, categories, "未分类"))',published:'if(date, date, pubDate)'};
  const columns=['formula.article','formula.category','note.tags','formula.published','note.draft'];
  const views=[{name:'全部文章'},{name:'按分类',group:true},{name:'草稿',draft:true}];
  const base=['# Generated by Deepsidian. Original articles are not modified.','filters:','  and:',...filters.map(f=>'    - '+yaml(f)),'formulas:',...Object.entries(formulas).map(([k,v])=>`  ${k}: ${yaml(v)}`),'properties:',...Object.entries({'formula.article':'文章','formula.category':'分类','note.tags':'标签','formula.published':'发布日期','note.draft':'草稿'}).flatMap(([k,v])=>[`  ${k}:`,`    displayName: ${yaml(v)}`]),'views:',...views.flatMap(v=>['  - type: table',`    name: ${yaml(v.name)}`,...(v.group?['    groupBy:','      property: formula.category','      direction: ASC']:[]),...(v.draft?['    filters:',`      and: [${yaml('draft == true')}]`]:[]),'    order:',...columns.map(c=>'      - '+c)]),''].join('\n');
  const missing={title:0,category:0,tags:0,published:0,draft:0};
  const groups=new Map<string,CatalogArticle[]>();
  for(const row of rows){
    const fm=row.frontmatter??{};
    if(!present(fm.title))missing.title++;
    if(!present(fm.category)&&!present(fm.categories))missing.category++;
    if(!present(fm.tags))missing.tags++;
    if(!present(fm.date)&&!present(fm.pubDate))missing.published++;
    if(typeof fm.draft!=='boolean')missing.draft++;
    const key=category(fm);groups.set(key,[...(groups.get(key)??[]),row]);
  }
  const navigation=['# 文章导航','',`扫描范围：${source?escapeLabel(source):'知识库根目录'}（排除 ${escapeLabel(output)}）。共 ${rows.length} 篇。`,'','这是生成时的静态导航；文章管理.base 会随文章属性变化更新。多分类文章在此按第一个分类归组。','',...Array.from(groups.entries()).sort(([a],[b])=>a.localeCompare(b)).flatMap(([name,items])=>[`## ${escapeLabel(name)}`,'',...items.map(a=>{
    const label=text(a.frontmatter?.title)||a.path.split('/').pop()!.replace(/\.md$/i,'');
    // Standard Markdown destinations encode #, brackets and whitespace without ambiguous wikilinks.
    const destination=a.path.split('/').map(s=>encodeURIComponent(s).replace(/[()']/g,c=>`%${c.charCodeAt(0).toString(16)}`)).join('/');
    const ups=output.split('/').map(()=> '..').join('/');
    return `- [${escapeLabel(label)}](${ups}/${destination})`;
  }), '']),'## 属性检查','',...Object.entries(missing).map(([key,n])=>`- ${key}：${n} 篇缺失${key==='draft'?'或不是布尔值':''}`),'','未推断分类、发布日期或学习掌握程度；未修改原文章。',''].join('\n');
  return {base,navigation,count:rows.length,missing};
}
